namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP 

image:
  repository: kpeeters89/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 3111

livenessProbe: 
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111 

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits: 
    cpu: 500m
    memory: 128Mi
