namespace:
  name: staging

service:
  port: 5111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP 

image:
  repository: kpeeters89/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

containerPort: 3111

livenessProbe: 
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111 

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits: 
    cpu: 500m
    memory: 128Mi
